apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event-exporter
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '2112'
        prometheus.io/path: '/metrics'
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: event-exporter
          # The good practice would be to pin the version. This is just a reference so that we don't
          # have to update this file in each release.
          image: ghcr.io/resmoio/kubernetes-event-exporter:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
            - -kubeconfig=/etc/remote-access.kubeconfig
          volumeMounts:
            - mountPath: /data
              name: cfg
            - name: remote-access
              mountPath: /etc/remote-access.kubeconfig
              subPath: remote-access.kubeconfig
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
      volumes:
        - name: cfg
          configMap:
            name: event-exporter-cfg
        - name: remote-access
          configMap:
            name: remote-access
  selector:
    matchLabels:
      app: event-exporter
      version: v1