# Default values for kok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
hub: "buxiaomo/kok"
tag: "1.0.0"

database:
  type: "sqlite"
  url: "/app/data/kok.sqlite"

prometheus:
  url: "http://127.0.0.1:9090"
elasticsearch:
  url: "http://127.0.0.1:9200"