{
 "title": "Kok Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "clusterName", "label": "clusterName", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({clusterName=\"$clusterName\"},nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU使用核",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{clusterName=~\"$clusterName\",resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{clusterName=~\"$clusterName\",id=\"/\"}[2m]))",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{clusterName=~\"$clusterName\",resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{clusterName=~\"$clusterName\",container!=\"\"})",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "节点网络总览",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{clusterName=~\"$clusterName\"}[2m]))by (node) *8",
     "legendFormat": "流入:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{clusterName=~\"$clusterName\"}[2m]))by (node) *8",
     "legendFormat": "流出:{{node}}"
    }
   ]
  },
  {
   "title": "命名空间资源统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{clusterName=~\"$clusterName\",node=~\"^$node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{clusterName=~\"$clusterName\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation\",clusterName=~\"$clusterName\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_daemonset_metadata_generation|\",clusterName=~\"$clusterName\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_statefulset_metadata_generation\",clusterName=~\"$clusterName\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{clusterName=~\"$clusterName\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{clusterName=~\"$clusterName\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{clusterName=~\"$clusterName\",resource=\"cpu\"})/ sum(kube_node_status_allocatable{clusterName=~\"$clusterName\",resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{clusterName=~\"$clusterName\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{clusterName=~\"$clusterName\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{clusterName=~\"$clusterName\",resource=\"cpu\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{clusterName=~\"$clusterName\",resource=\"cpu\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{clusterName=~\"$clusterName\",resource=\"memory\"}) / sum(kube_node_status_allocatable{clusterName=~\"$clusterName\",resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", clusterName=\"$clusterName\"})  by (instance, cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\", clusterName=\"$clusterName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{clusterName=\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{clusterName=~\"$clusterName\"})"
    }
   ]
  },
  {
   "title": "Mem Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\",clusterName=\"$clusterName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{clusterName=~\"$clusterName\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{clusterName=~\"$clusterName\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{clusterName=~\"$clusterName\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{clusterName=~\"$clusterName\", phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "CPU Load 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(node_load1{job=\"node-exporter\",clusterName=\"$clusterName\"}) by (instance) / count(node_cpu_seconds_total{job=\"node-exporter\",clusterName=\"$clusterName\", mode=\"system\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node NotReady",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{clusterName=\"$clusterName\",condition=\"Ready\",status=\"false\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{job=\"node-exporter\",clusterName=\"$clusterName\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "etcd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"etcd\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"etcd\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "kube-apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-apiserver\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-apiserver\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Server QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{job=\"kube-apiserver\",clusterName=~\"^$clusterName$\"}[5m]))",
     "legendFormat": "APIServer QPS"
    }
   ]
  },
  {
   "title": "Request Duration Seconds(99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=\"GET\",resource!=\"\",subresource!~\"log|proxy\",clusterName=~\"^$clusterName$\"}[5m])) by (verb,le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb=\"LIST\",clusterName=~\"^$clusterName$\"}[5m])) by (verb, le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(apiserver_request_duration_seconds_bucket{job=\"kube-apiserver\",verb!~\"GET|WATCH|LIST|CONNECT\",clusterName=~\"^$clusterName$\"}[5m])) by (le))",
     "legendFormat": "WRITE"
    }
   ]
  },
  {
   "title": "API Server Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"kube-apiserver\",code=~\"^(?:5..)$\",clusterName=~\"^$clusterName$\"}[1m])) / sum(rate(apiserver_request_total{job=\"kube-apiserver\",clusterName=~\"^$clusterName$\"}[1m])) * 100",
     "legendFormat": "APIServer error rate"
    }
   ]
  },
  {
   "title": "API Server Current Inflight Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apiserver_current_inflight_requests{job=\"kube-apiserver\",clusterName=~\"^$clusterName$\"}",
     "legendFormat": "{{request_kind}}"
    }
   ]
  },
  { "title": "kube-controller-manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-controller-manager\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-controller-manager\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Controller Manager Workqueue Queue Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"kube-controller-manager\", clusterName=~\"^$clusterName$\"}[5m])) by (name, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Controller Manager To API Server Request Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-controller-manager\",clusterName=~\"^$clusterName$\"}[5m])) by (verb,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "kube-scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-scheduler\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-scheduler\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Scheduler Pending Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "scheduler_pending_pods{job=\"kube-scheduler\",clusterName=~\"^$clusterName$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  { "title": "kube-proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-proxy\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-proxy\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "kubelet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubelet\",clusterName=\"$clusterName\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kubelet\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CoreDNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "CoreDNS - Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 100 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"coredns\", clusterName=\"$clusterName\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"coredns\" ,clusterName=\"$clusterName\"}[$__rate_interval]) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CoreDNS Panic Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(coredns_panics_total{clusterName=~\"^$clusterName$\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CoreDNS Request Duration Seconds(99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_duration_seconds_bucket{job=\"coredns\",clusterName=~\"^$clusterName$\"}[5m])) by(server, zone, le))",
     "legendFormat": "server=\"{{server}}\", zone=\"{{zone}}\""
    }
   ]
  },
  {
   "title": "Cache hits rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "bottomk(10, sum by(instance) (rate(coredns_cache_hits_total{job=\"coredns\",clusterName=~\"^$clusterName$\"}[5m])) / sum by(instance) (rate(coredns_dns_requests_total{job=\"coredns\",clusterName=~\"^$clusterName$\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}