{
 "title": "Kok Services",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "clusterName", "label": "clusterName", "query": { "query": "label_values(clusterName)" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({clusterName=\"$clusterName\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$clusterName\", namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_container_info{clusterName=~\"$clusterName\", namespace=~\"$namespace\", container=~\"$application\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{clusterName=\"$clusterName\", namespace=\"$namespace\", pod=\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pods CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods CPU Usage(Cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods CPU Rate Of Utilization(usage/resourceLimits)",
   "type": "timeseries",
   "description": "Only display applications that have CPU resource limit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{clusterName=~\"^$clusterName\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) by (pod)) / (sum(kube_pod_container_resource_limits{resource=\"cpu\",clusterName=~\"^$clusterName\",namespace=~\"$namespace\",pod=~\"$pod\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pods Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Memory Rate Of Utilization(workingSet/resourceLimits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum (container_memory_working_set_bytes{clusterName=~\"^$clusterName\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}) by (pod)) / (sum (kube_pod_container_resource_limits{resource=\"memory\",clusterName=~\"^$clusterName\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods Network Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pods Network Utilization  Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) without (interface)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Network Utilization  Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) without (interface)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Disk I/O utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Disk I/O utilization Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O utilization Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{clusterName=~\"^$clusterName$\",namespace=~\"$namespace\", container=~\"$container\",pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}