apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |-
    # my global config
    global:
      external_labels:
        clusterName: {{ .Values.clusterName }}-{{ .Values.clusterEnv }}
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "kube-state-metrics"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_container_port_name]
            action: keep
            regex: kube-system;kube-state-metrics;http-metrics

      - job_name: "node-exporter"
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: replace
            source_labels: [__address__]
            regex: "(.*):10250"
            replacement: "${1}:9100"
            target_label: __address__

      - job_name: "coredns"
        honor_labels: true
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
            separator: "/"
            regex: "kube-system/coredns.+"
          - source_labels:
              - __meta_kubernetes_pod_container_port_name
            action: keep
            regex: metrics
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
    
      - job_name: "kube-proxy"
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        follow_redirects: true
        enable_http2: true
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: replace
            source_labels: [__address__]
            regex: "(.*):10250"
            replacement: "${1}:10249"
            target_label: __address__

      - job_name: "kubelet"
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

    remote_write:
      - url: "{{ .Values.remoteWrite }}/api/v1/write"
        remote_timeout: 30s
        tls_config:
          insecure_skip_verify: true
        queue_config:
          capacity: 500
          max_shards: 1000
          min_shards: 1
          max_samples_per_send: 100
          batch_send_deadline: 5s
          min_backoff: 30ms
          max_backoff: 100ms
