apiVersion: apps/v1
kind: Deployment
metadata:
  name: kok
  labels:
    app: kok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kok
  template:
    metadata:
      labels:
        app: kok
    spec:
      serviceAccount: kok
      containers:
        - name: kok
          image: "docker.m.moby.org.cn/{{ .Values.hub }}:{{ .Values.tag }}"
          imagePullPolicy: Always
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 8080
#          resources:
#            limits:
#              cpu: "2"
#              memory: "1Gi"
#            requests:
#              cpu: "60m"
#              memory: "850Mi"
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: GIN_MODE
              value: "release"
            - name: WEBHOOK_URL
              value: "{{ .Values.webhookUrl }}"