kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-vol
  labels:
    app: elasticsearch
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    name: elasticsearch
  type: LoadBalancer
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: rest
      port: 9300
      targetPort: 9300

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      name: elasticsearch
      labels:
        name: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-vol
          persistentVolumeClaim:
            claimName: elasticsearch-vol
      initContainers:
        - name: fix-permissions
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-vol
              mountPath: /usr/share/elasticsearch/data
          securityContext:
            privileged: true
        - name: increase-vm-max-map
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "ulimit -n 65536"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.22
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: rest
              containerPort: 9300
              protocol: TCP
          # resources:
          #   limits:
          #     cpu: "230m"
          #     memory: "700Mi"
          #   requests:
          #     cpu: "25m"
          #     memory: "70Mi"
          volumeMounts:
            - name: elasticsearch-vol
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: discovery.type
              value: "single-node"
