kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: conf-vol
  labels:
    app: conf-vol
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi