apiVersion: v1
kind: ServiceAccount
metadata:
  name: kok
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application:kok
rules:
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - delete
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - patch
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - delete
      - create
      - patch
      - get
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - delete
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - delete
      - create
      - patch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: application:kok
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application:kok
subjects:
  - kind: ServiceAccount
    name: kok
    namespace: {{ .Release.Namespace }}