apiVersion: v1
kind: ServiceAccount
metadata:
  name: kok
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: application:kok
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: application:kok
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: application:kok
subjects:
  - kind: ServiceAccount
    name: kok
    namespace: {{ .Release.Namespace }}