apiVersion: v1
kind: ServiceAccount
metadata:
  name: antrea-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: antrea
---
# Source: antrea/templates/antctl/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: antctl
  namespace: {{ .Release.Namespace }}
  labels:
    app: antrea
---
# Source: antrea/templates/controller/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: antrea-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: antrea