apiVersion: v1
kind: Secret
metadata:
  name: antrea-agent-service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: antrea-agent
type: kubernetes.io/service-account-token
---
# Source: antrea/templates/antctl/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: antctl-service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: antctl
type: kubernetes.io/service-account-token