name: Publish Package

on:
  push:

permissions:
  packages: write
  attestations: write
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: "ghcr.io"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build images
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use --bootstrap --name multi-platform --driver docker-container
          docker buildx build --platform=amd64,arm64 -t ghcr.io/buxiaomo/kok:${GITHUB_SHA::6} --push .
