name: Publish Package

on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker buildx create --use --name mybuild node-amd64
          docker buildx create --append --name mybuild node-arm64
          docker buildx build --platform=amd64,arm64 -t ghcr.io/buxiaomo/kok:${GITHUB_SHA::6} --push .
