---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus
          configMap:
            name: prometheus
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v2.53.1
          imagePullPolicy: Always
          volumeMounts:
            - name: prometheus
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9090
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            tcpSocket:
              port: 9090
          env:
            - name: TZ
              value: "Asia/Shanghai"
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "512Mi"